-- liquibase formatted sql

-- changeset eve-corp-manager:002-identity-tenant-auth
-- comment EVE 国服角色、军团、租户成员、授权、权限快照及授权审计数据模型
CREATE TABLE `eve_corporation` (
    `id` bigint AUTO_INCREMENT COMMENT 'ID',
    `tenant_id` bigint NOT NULL COMMENT '租户ID',
    `server` varchar(20) NOT NULL COMMENT '服务器代码',
    `corporation_id` bigint NOT NULL COMMENT 'EVE军团ID',
    `name` varchar(100) NOT NULL COMMENT '军团名称',
    `ticker` varchar(20) DEFAULT NULL COMMENT '军团简称',
    `ceo_character_id` bigint DEFAULT NULL COMMENT 'CEO角色ID',
    `alliance_id` bigint DEFAULT NULL COMMENT '联盟ID',
    `member_count` int DEFAULT NULL COMMENT '成员数量',
    `tax_rate` decimal(6,5) DEFAULT NULL COMMENT '税率',
    `status` varchar(20) NOT NULL DEFAULT 'ACTIVE' COMMENT '状态',
    `last_synced_at` datetime DEFAULT NULL COMMENT '最后同步时间',
    `create_user` bigint NOT NULL COMMENT '创建人',
    `create_time` datetime NOT NULL COMMENT '创建时间',
    `update_user` bigint DEFAULT NULL COMMENT '修改人',
    `update_time` datetime DEFAULT NULL COMMENT '修改时间',
    `deleted` bigint NOT NULL DEFAULT 0 COMMENT '是否已删除（0：否；id：是）',
    PRIMARY KEY (`id`),
    UNIQUE INDEX `uk_eve_corporation_server_id` (`server`, `corporation_id`, `deleted`),
    UNIQUE INDEX `uk_eve_corporation_tenant` (`tenant_id`, `deleted`),
    INDEX `idx_eve_corporation_ceo` (`server`, `ceo_character_id`),
    INDEX `idx_eve_corporation_status` (`status`),
    INDEX `idx_eve_corporation_deleted` (`deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='EVE军团租户绑定表';

CREATE TABLE `eve_character` (
    `id` bigint AUTO_INCREMENT COMMENT 'ID',
    `tenant_id` bigint NOT NULL COMMENT '租户ID',
    `user_id` bigint NOT NULL COMMENT '本站用户ID',
    `server` varchar(20) NOT NULL COMMENT '服务器代码',
    `character_id` bigint NOT NULL COMMENT 'EVE角色ID',
    `corporation_id` bigint NOT NULL COMMENT 'EVE军团ID',
    `owner_hash` varchar(128) NOT NULL COMMENT 'SSO角色所有者校验摘要',
    `name` varchar(100) NOT NULL COMMENT '角色名称',
    `status` varchar(20) NOT NULL DEFAULT 'ACTIVE' COMMENT '角色绑定状态',
    `is_primary` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否为主角色',
    `joined_at` datetime DEFAULT NULL COMMENT '加入军团时间',
    `last_verified_at` datetime DEFAULT NULL COMMENT '最后身份验证时间',
    `create_user` bigint NOT NULL COMMENT '创建人',
    `create_time` datetime NOT NULL COMMENT '创建时间',
    `update_user` bigint DEFAULT NULL COMMENT '修改人',
    `update_time` datetime DEFAULT NULL COMMENT '修改时间',
    `deleted` bigint NOT NULL DEFAULT 0 COMMENT '是否已删除（0：否；id：是）',
    PRIMARY KEY (`id`),
    UNIQUE INDEX `uk_eve_character_server_id` (`server`, `character_id`, `deleted`),
    INDEX `idx_eve_character_owner` (`server`, `owner_hash`),
    INDEX `idx_eve_character_tenant_user` (`tenant_id`, `user_id`),
    INDEX `idx_eve_character_tenant_corp` (`tenant_id`, `corporation_id`),
    INDEX `idx_eve_character_status` (`tenant_id`, `status`),
    INDEX `idx_eve_character_deleted` (`deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='EVE角色绑定表';

CREATE TABLE `eve_corporation_member` (
    `id` bigint AUTO_INCREMENT COMMENT 'ID',
    `tenant_id` bigint NOT NULL COMMENT '租户ID',
    `corporation_ref_id` bigint NOT NULL COMMENT 'EVE军团绑定记录ID',
    `character_ref_id` bigint NOT NULL COMMENT 'EVE角色绑定记录ID',
    `user_id` bigint NOT NULL COMMENT '本站用户ID',
    `status` varchar(20) NOT NULL DEFAULT 'ACTIVE' COMMENT '成员状态',
    `joined_at` datetime DEFAULT NULL COMMENT '加入军团时间',
    `left_at` datetime DEFAULT NULL COMMENT '离开军团时间',
    `last_verified_at` datetime DEFAULT NULL COMMENT '最后成员身份验证时间',
    `create_user` bigint NOT NULL COMMENT '创建人',
    `create_time` datetime NOT NULL COMMENT '创建时间',
    `update_user` bigint DEFAULT NULL COMMENT '修改人',
    `update_time` datetime DEFAULT NULL COMMENT '修改时间',
    `deleted` bigint NOT NULL DEFAULT 0 COMMENT '是否已删除（0：否；id：是）',
    PRIMARY KEY (`id`),
    UNIQUE INDEX `uk_eve_corp_member_character` (`tenant_id`, `character_ref_id`, `deleted`),
    INDEX `idx_eve_corp_member_corporation` (`tenant_id`, `corporation_ref_id`, `status`),
    INDEX `idx_eve_corp_member_user` (`tenant_id`, `user_id`, `status`),
    INDEX `idx_eve_corp_member_deleted` (`deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='EVE军团成员关系表';

CREATE TABLE `eve_authorization` (
    `id` bigint AUTO_INCREMENT COMMENT 'ID',
    `tenant_id` bigint NOT NULL COMMENT '租户ID',
    `character_ref_id` bigint NOT NULL COMMENT 'EVE角色绑定记录ID',
    `user_id` bigint NOT NULL COMMENT '本站用户ID',
    `server` varchar(20) NOT NULL COMMENT '服务器代码',
    `scopes` json NOT NULL COMMENT '已授权OAuth Scope集合',
    `access_token` mediumtext DEFAULT NULL COMMENT '加密后的访问令牌',
    `refresh_token` mediumtext DEFAULT NULL COMMENT '加密后的刷新令牌',
    `token_type` varchar(20) NOT NULL DEFAULT 'Bearer' COMMENT '令牌类型',
    `expires_at` datetime NOT NULL COMMENT '访问令牌过期时间',
    `refresh_expires_at` datetime DEFAULT NULL COMMENT '刷新令牌过期时间',
    `status` varchar(30) NOT NULL DEFAULT 'ACTIVE' COMMENT '授权状态',
    `revoked_at` datetime DEFAULT NULL COMMENT '撤销时间',
    `failure_count` int NOT NULL DEFAULT 0 COMMENT '连续失败次数',
    `failure_code` varchar(100) DEFAULT NULL COMMENT '脱敏后的最后失败代码',
    `last_verification_status` varchar(30) NOT NULL DEFAULT 'PENDING' COMMENT '最后验证状态',
    `last_verified_at` datetime DEFAULT NULL COMMENT '最后验证时间',
    `create_user` bigint NOT NULL COMMENT '创建人',
    `create_time` datetime NOT NULL COMMENT '创建时间',
    `update_user` bigint DEFAULT NULL COMMENT '修改人',
    `update_time` datetime DEFAULT NULL COMMENT '修改时间',
    `deleted` bigint NOT NULL DEFAULT 0 COMMENT '是否已删除（0：否；id：是）',
    PRIMARY KEY (`id`),
    UNIQUE INDEX `uk_eve_authorization_character` (`tenant_id`, `character_ref_id`, `deleted`),
    INDEX `idx_eve_authorization_user` (`tenant_id`, `user_id`),
    INDEX `idx_eve_authorization_status` (`tenant_id`, `status`, `expires_at`),
    INDEX `idx_eve_authorization_verify` (`last_verification_status`, `last_verified_at`),
    INDEX `idx_eve_authorization_deleted` (`deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='EVE国服授权表';

CREATE TABLE `eve_character_role_snapshot` (
    `id` bigint AUTO_INCREMENT COMMENT 'ID',
    `tenant_id` bigint NOT NULL COMMENT '租户ID',
    `character_ref_id` bigint NOT NULL COMMENT 'EVE角色绑定记录ID',
    `server` varchar(20) NOT NULL COMMENT '服务器代码',
    `character_id` bigint NOT NULL COMMENT 'EVE角色ID',
    `is_ceo` bit(1) NOT NULL DEFAULT b'0' COMMENT '采集时是否为军团CEO',
    `roles` json NOT NULL COMMENT '全局军团角色',
    `roles_at_hq` json NOT NULL COMMENT '总部军团角色',
    `roles_at_base` json NOT NULL COMMENT '基地军团角色',
    `roles_at_other` json NOT NULL COMMENT '其他地点军团角色',
    `captured_at` datetime NOT NULL COMMENT '快照采集时间',
    `source_expires_at` datetime DEFAULT NULL COMMENT 'ESI缓存过期时间',
    `create_user` bigint NOT NULL COMMENT '创建人',
    `create_time` datetime NOT NULL COMMENT '创建时间',
    `update_user` bigint DEFAULT NULL COMMENT '修改人',
    `update_time` datetime DEFAULT NULL COMMENT '修改时间',
    `deleted` bigint NOT NULL DEFAULT 0 COMMENT '是否已删除（0：否；id：是）',
    PRIMARY KEY (`id`),
    INDEX `idx_eve_role_snapshot_character` (`tenant_id`, `character_ref_id`, `captured_at`),
    INDEX `idx_eve_role_snapshot_external` (`server`, `character_id`, `captured_at`),
    INDEX `idx_eve_role_snapshot_deleted` (`deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='EVE角色权限快照表';

CREATE TABLE `eve_auth_audit` (
    `id` bigint AUTO_INCREMENT COMMENT 'ID',
    `tenant_id` bigint DEFAULT NULL COMMENT '租户ID，认领前授权失败事件可为空',
    `authorization_id` bigint DEFAULT NULL COMMENT '授权记录ID',
    `character_ref_id` bigint DEFAULT NULL COMMENT 'EVE角色绑定记录ID',
    `user_id` bigint DEFAULT NULL COMMENT '本站用户ID',
    `event_type` varchar(40) NOT NULL COMMENT '授权事件类型',
    `result` varchar(20) NOT NULL COMMENT '事件结果',
    `request_id` varchar(64) DEFAULT NULL COMMENT '请求追踪ID',
    `client_ip` varchar(64) DEFAULT NULL COMMENT '客户端IP',
    `user_agent` varchar(500) DEFAULT NULL COMMENT '客户端标识',
    `detail` varchar(1000) DEFAULT NULL COMMENT '脱敏后的审计详情',
    `occurred_at` datetime NOT NULL COMMENT '事件发生时间',
    `create_user` bigint NOT NULL COMMENT '创建人',
    `create_time` datetime NOT NULL COMMENT '创建时间',
    `update_user` bigint DEFAULT NULL COMMENT '修改人',
    `update_time` datetime DEFAULT NULL COMMENT '修改时间',
    `deleted` bigint NOT NULL DEFAULT 0 COMMENT '是否已删除（0：否；id：是）',
    PRIMARY KEY (`id`),
    INDEX `idx_eve_auth_audit_authorization` (`tenant_id`, `authorization_id`, `occurred_at`),
    INDEX `idx_eve_auth_audit_character` (`tenant_id`, `character_ref_id`, `occurred_at`),
    INDEX `idx_eve_auth_audit_user` (`tenant_id`, `user_id`, `occurred_at`),
    INDEX `idx_eve_auth_audit_request` (`request_id`),
    INDEX `idx_eve_auth_audit_event` (`event_type`, `result`, `occurred_at`),
    INDEX `idx_eve_auth_audit_deleted` (`deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='EVE授权审计表';
